[package]
name = "basic-calc"
version = "1.0.4"
license = "GPL-3.0"
edition = "2021"
description = "Basic TUI calculator"
repository = "https://github.com/ePog123/rust-calc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
